about/urls.py
from django.urls import path
from . import views

app_name = 'about'
urlpatterns = [
    path('',views.index, name='index'),
]

careers/urls.py
from django.urls import path
from . import views

app_name = 'careers'
urlpatterns = [
    path('',views.index, name='index'),
    path('application/',views.create_application, name='create_application'),
]

contacts/urls.py
from django.urls import path
from . import views

app_name = 'contacts'
urlpatterns = [
     path('', views.index, name='index'),
     path('message/', views.create_message, name='create_message'),
]

fi_opc/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('careers/', include('careers.urls')),
    path('contacts/', include('contacts.urls')),
    path('services/', include('services.urls')),
    path('licenses-certificates/', include('licenses_certificates.urls')),
    path('', include('home.urls')),
    path('partners/', include('partners.urls')),
    path('about/', include('about.urls')),
    path('major-clients/', include('major_clients.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('',views.index, name='index'),
]

licenses_certificates/urls.py
from django.urls import path
from . import views

app_name = 'licenses_certificates'
urlpatterns = [
    path('',views.index, name='index'),
]

major_clients/urls.py
from django.urls import path
from . import views

app_name = 'major_clients'
urlpatterns = [
    path('',views.index, name='index'),
]

partners/urls.py
from django.urls import path
from . import views

app_name = 'partners'
urlpatterns = [
    path('',views.index, name='index'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('',views.index, name='index'),
]

services/urls.py
from django.urls import path
from . import views

app_name = 'services'
urlpatterns = [
    path('',views.index, name='index'),
    path('consulting-services/',views.display_consulting_services, name='consulting-services'),
    path('rehabilitation/',views.display_rehabilitation, name='rehabilitation'),
    path('technology-upgrade/',views.display_technology_upgrade, name='technology-upgrade'),
    path('engineering-services/',views.display_engineering_services, name='engineering-services'),
    path('operations-and-maintenance/',views.display_operations_and_maintenance, name='operations-and-maintenance'),
    path('design-and-build/',views.display_design_and_build, name='design-and-build'),
]

careers/models.py
from django.db import models

class JobOpportunity(models.Model):
    title = models.CharField(max_length=255)
    company_name = models.CharField(max_length=255)
    description = models.TextField()
    qualifications = models.TextField(blank=True)
    requirements = models.TextField(blank=True)

    def __str__(self):
        return f"{self.company_name} - {self.title}"

class Application(models.Model):
    job = models.ForeignKey(JobOpportunity, on_delete=models.CASCADE, default=None)
    full_name = models.CharField(max_length=255)
    email = models.EmailField()
    additional_info = models.TextField(blank=True)
    cv = models.FileField(upload_to='files')

    def __str__(self):
        return f"{self.full_name} - {self.job}"

contacts/models.py
from django.db import models

class ContactMessage(models.Model):
    full_name = models.CharField(max_length=255)
    email = models.EmailField()
    company = models.CharField(max_length=255)
    position = models.CharField(max_length=255)
    message = models.TextField(blank=True, null=True)
    contact_num = models.CharField(max_length=20)

    submitted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.full_name} - {self.email}"

major_clients/models.py
from django.db import models

# Create your models here.

about/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, "about/about.html")

careers/views.py
from django.http import JsonResponse
from django.urls import reverse
from .models import Application, JobOpportunity
from django.shortcuts import redirect, render
from django.contrib import messages

def index(request):
    try:
        jobs = JobOpportunity.objects.all()
    except:
        return JsonResponse({'error': 'Something went wrong'})
    return render(request, 'careers/careers.html', {'jobs': jobs})

def create_application(request):
    try:

        jobs = JobOpportunity.objects.all()
        if request.method == 'POST':
            full_name = request.POST.get('full_name')
            email = request.POST.get('email')
            additional_info = request.POST.get('additional_info')
            cv_file = request.FILES.get('cv')
            job_id = request.POST.get('job_id')

            job = JobOpportunity.objects.get(id=job_id)

            Application.objects.create(
                full_name=full_name,
                email=email,
                additional_info=additional_info,
                cv=cv_file,
                job=job
            )
            messages.success(request, 'Application submitted successfully')
            #return redirect(reverse('careers:index'), {'isSuccess': True})
            return render(request, 'careers/careers.html', {'isSuccess': True, "jobs": jobs})
        else:
            return redirect(reverse('careers:index'), {'isSuccess': False})
    except:
        return JsonResponse({'error': 'Something went wrong'})
    

contacts/views.py
from django.shortcuts import render, redirect
from .models import ContactMessage
from django.contrib import messages
from django.http import JsonResponse
from django.urls import reverse

def index(request):
    return render(request, "contacts/contacts.html")
def create_message(request):
    try:
        if request.method == "POST":
            full_name = request.POST.get("full_name")
            email = request.POST.get("email")
            company = request.POST.get("company")
            position = request.POST.get("position")
            message = request.POST.get("message")
            contact_num = request.POST.get("contact-num")

            ContactMessage.objects.create(
                full_name=full_name,
                email=email,
                company=company,
                position=position,
                message=message,
                contact_num=contact_num,
            )
            messages.success(request, 'Message submitted successfully')
            return render(request, "contacts/contacts.html", {"isSuccess": True})
            #return redirect(reverse('contacts:index'), {"isSuccess": True})
        else:
            return render(request, "contacts/contacts.html", {"isSuccess": False})
    except Exception as e:
        print("Error:", e)
        return JsonResponse({'error': 'Something went wrong'})

home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "home/home.html")

licenses_certificates/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'licenses_certificates/licenses-certificates.html')

major_clients/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, "major_clients/major_clients.html")

partners/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "partners/partners.html")

products/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'products/products.html')

services/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "services/services.html")

def display_consulting_services(request):
    return render(request, "services/consulting-services.html")

def display_engineering_services(request):
    return render(request, "services/engineering-services.html")

def display_rehabilitation(request):
    return render(request, "services/rehabilitation.html")

def display_technology_upgrade(request):
    return render(request, "services/technology-upgrade.html")

def display_operations_and_maintenance(request):
    return render(request, "services/operations-and-maintenance.html")

def display_design_and_build(request):
    return render(request, "services/design-and-build.html")

about/templates/about/about.html
{% extends 'base.html' %}
{% block maincontent %}
{% load static %}

<div class="about">

  <div class="title"><p>ABOUT US</p></div>

  <div class="about-us">
    <p>
      Founded in 2025, Flow Industries OPC emerges as a dedicated environmental specialty contractor, expanding the esteemed legacy of its parents company. Established to specifically address advanced water treatment needs, Flow represents parent company's stragetic initiative to specialize and innovate within the environment sector.
      <br><br>
      Conceived by its visionary founder, a passionate biologist enriched by extensive hands-on experience in the industry. Flow is dedicated to revolutionizing wastewater treatment by prioritizing purely biological and organic methodologies, reserving chemical solutions as a secondary alternatives.
      <br><br>
      Our multidisciplinary team unites experts from science, engineering, architecture, and technology, allowing us to seamlessly integrate cutting-edge advancements with sustainable biological techniques. This synergistic approach ensures that our water treatment systems are not only groundbreaking and highly effective but also environmentally sustainable.
      <br><br>
      Flow continuously expands its horizons through rigorous research and development initiatives, hiring professionals, strategic joint ventures, and persistent innovation aimed at achieving global competitiveness.
    </p>
  </div>

  <div class="txt-container">
    <div class="section">
      <div class="txt-title"><p>MISSION</p></div>
      <div class="mission">
        <p>To choose a noble work that serve others.</p>
      </div>
    </div>

    <div class="section">
      <div class="txt-title title-vision"><p>VISION</p></div>
      <div class="vision">
        <p>Be the best organization in the Philippines.</p>
      </div>
    </div>

    <div class="section">
      <div class="txt-title title-core-values"><p>CORE VALUES</p></div>
      <div class="core-values">
        <p>
          Capable: Give all our best in every work.<br>
          Trustworthy: Maintain integrity on ourselves.<br>
          Incorruptible: Being faithful.<br>
          God Fearing: Putting faith in every works.
        </p>
      </div>
    </div>

    <div class="section">
      <div class="txt-title title-core-ideology"><p>CORE IDEOLOGY</p></div>
      <div class="core-ideology">
        <p>
          We measure our success by how many people we've helped along the way.
        </p>
      </div>
    </div>
  </div>

</div>

<div class="certs">
  <div class="title">
    <p>LICENSES AND CERTIFICATES</p>
  </div>

  <div class="grid-container">
    <div class="grid-item">
      <img src="{% static 'images/barangay-clearance.png' %}" alt="Barangay Clearance">
      <div class="name">Barangay Clearance</div>
    </div>
    <div class="grid-item">
      <img src="{% static 'images/sec-registration.png' %}" alt="SEC Registration">
      <div class="name">SEC Registration</div>
    </div>
    <div class="grid-item">
      <img src="{% static 'images/bus-permit.png' %}" alt="Bus Permit">
      <div class="name">Bus Permit</div>
    </div>
    <div class="grid-item">
      <img src="{% static 'images/bir-cert-1.png' %}" alt="BIR Certificate of Registration">
      <div class="name">BIR Certificate of Registration (1)</div>
    </div>
    <div class="grid-item">
      <img src="{% static 'images/bir-cert-2.png' %}" alt="BIR Certificate of Registration">
      <div class="name">BIR Certificate of Registration (2)</div>
    </div>
    <div class="grid-item">
      <img src="{% static 'images/bir-cert-3.png' %}" alt="BIR Certificate of Registration">
      <div class="name">BIR Certificate of Registration (3)</div>
    </div>
  </div>

  <div id="imageModal" class="modal">
    <span class="close">&times;</span>
    <img class="modal-content" id="modalImage">
  </div>
</div>

<script>
  const modal = document.getElementById("imageModal");
  const modalImg = document.getElementById("modalImage");
  const closeBtn = document.querySelector(".close");
  document.querySelectorAll(".grid-item img").forEach(img => {
    img.addEventListener("click", () => {
      modal.style.display = "block";
      modalImg.src = img.src;
      modalImg.alt = img.alt;
    });
  });
  closeBtn.addEventListener("click", () => {
    modal.style.display = "none";
  });
  window.addEventListener("click", (e) => {
    if (e.target === modal) {
      modal.style.display = "none";
    }
  });
</script>

{% endblock %}

careers/templates/careers/careers.html
{% extends 'base.html'%}
{% block maincontent %}
{% load static %}
<div class="careers">
  <h1>Join Our Mission to Transform Water<br>for a Better Tomorrow</h1>
  <p class="careers-description">
    At Flow Industries OPC, we are driven by a noble mission — to serve others through meaningful work that creates cleaner, healthier communities. Guided by our vision to become the leading organization in the Philippines, we uphold strong values: being capable, trustworthy, incorruptible, and God-fearing.<br><br>
    Whether you're a fresh graduate or a seasoned expert, you'll be a part of a purpose-driven team that values integrity, growth, and collaboration. We believe that attitude comes first, talent follows, and profit is the result — because who we are matters most.<br><br>
    Start your journey with us — where every drop matters, and so does every team member.
  </p>

  <h2 class="open-positions">Open Positions</h2>
  {% for job in jobs %}
  <div class="collapsible-container">
    <div class="collapsible-header" onclick="toggleCollapse(this)">
      <h2>{{ job.title }}</h2>
      <span class="arrow"><img src="{% static 'images/down-arrow.png' %}"></span>
    </div>

    <div class="company-description">
      <p>{{ job.description }}</p>
    </div>

    <div class="collapsible-content">
      {% if job.qualifications %}
      <p><strong>Job Qualifications:</strong></p>
      {% endif %}
      <ul>
        {% for q in job.qualifications.splitlines %}
          <li>{{ q }}</li>
        {% endfor %}
      </ul>
      {% if job.requirements %}
      <p><strong>Job Requirements:</strong></p>
      <ul>
      {% endif %}
      {% for r in job.requirements.splitlines %}
        <li>{{ r }}</li>
      {% endfor %}
      </ul>
      <a href="#" class="apply-button" onclick="openCareersModal({{ job.id }})">APPLY NOW</a>
    </div>

  </div>

  {% comment %} Application Form {% endcomment %}
  <div class="modal-overlay" id="careersModalOverlay">
    <div class="modal">
      <span class="close-btn" onclick="closeCareersModal()">&times;</span>
      <h2>APPLICATION FORM</h2>
      <form action="{% url 'careers:create_application' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="job_id" id="job_id_input" value={{job.id}}>
        <input type="text" placeholder="Full Name" name="full_name" required>
        <input type="email" placeholder="Email" name="email" required>
        <textarea placeholder="Additional Information" name="additional_info"></textarea>
        <div>
          <label>Upload your CV</label><br>
          <input type="file" name="cv">
        </div>
        <button type="submit" class="submit-btn">SUBMIT</button>
      </form>      
    </div>
  </div>
  {% endfor %}

  {% comment %} successful application modal {% endcomment %}
  {% if isSuccess %}
  <div class="success-modal-overlay" id="careersSuccessModal" style="display: block;">
    <div class="success-modal">
      <span class="close-btn" onclick="closeCareersSuccessModal()">&times;</span>
      <h2>Application Submitted!</h2>
      <p>Thank you for applying. We’ll get back to you soon.</p>
    </div>
  </div>
  {% endif %}
</div>

<br><br><br><br>

{% endblock %}

contacts/templates/contacts/contacts.html
{% extends 'base.html'%}
{% block maincontent %}
{% load static %}

<div class="contacts">

  <h1 class="contacts-heading">NEED A WATER-TREATMENT SOLUTION?</h1>
  <h3>Your solution starts here. We'll reply within 24 hours!</h3>

  <div class="info-and-form">
    <!-- Left: Contact Info -->
    <div class="modal">
      <h2>Request a FREE ocular inspection and quotation!</h2>
      <p>SEND US A MESSAGE</p>
      <form action="{% url 'contacts:create_message' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
          <input type="text" placeholder="Full Name" name="full_name" required>
          <input type="email" placeholder="Email" name="email" required>
        </div>
        <div class="form-row">
          <input type="text" placeholder="Company" name="company" required>
          <input type="text" placeholder="Position" name="position" required>
        </div>
        <textarea placeholder="Enter your message" name="message"></textarea>
        <input type="text" placeholder="Contact No." name="contact-num" required style="height:40px;">
        <button type="submit" class="submit-btn">SUBMIT</button>
      </form>
    </div>

    <!-- Right: Message Form -->

    <div class="contact-info">
      <h2>CONTACT US</h2>
      <div class="location">
        <img class="icon" src="{% static 'images/marker.png' %}">
        <p class="location-text">Unit F 6/F Westgate Tower Condo, Investment Dr., Madrigal Business Park, Ayala-Alabang, Muntinlupa 1780</p>
      </div>
      <div class="email">
        <img class="icon" src="{% static 'images/envelope.png' %}">
        <p class="email-text">flowindustriesopc@gmail.com</p>
      </div>
      <div class="phone">
        <img class="icon" src="{% static 'images/phone-call.png' %}">
        <p class="phone-text">(02) 8296 2844</p>
      </div>
      <div class="mobile">
        <img class="icon" src="{% static 'images/mobile-button.png' %}">
        <p class="mobile-text">+639-776-597-815</p>
      </div>
    </div>
  </div>

  <!-- Map Below -->
  <div class="map-section">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7728.035528225201!2d121.01826247895885!3d14.426139524655554!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3397d1cf7b8a3577%3A0x9b2a2beca0441db3!2s1761%20Investment%20Dr%2C%20Muntinlupa%2C%20Metro%20Manila!5e0!3m2!1sen!2sph!4v1746449261722!5m2!1sen!2sph"
      style="border:transparent;"></iframe>
  </div>

  {% if isSuccess %}
  <div class="success-modal-overlay" id="contactsSuccessModal" style="display: block;">
    <div class="success-modal">
      <span class="close-btn" onclick="closeContactsSuccessModal()">&times;</span>
      <h2>Message Submitted!</h2>
      <p>We'll get back to you as soon as possible.</p>
    </div>
  </div>
  {% endif %}
</div>

{% endblock%}

home/templates/home/home.html
{% extends 'base.html' %}
{% block maincontent %}
{% load static %}

<div class="home">

  <div class="carousel">
    <div class="carousel-inner">

      <!-- Slide 1 -->
      <div class="carousel-item active">
        <div class="text-content">
          <h2>Compact Sewage Treatment Plant (STP)</h2>
          <p>A modern, space-efficient STP solution designed and built by our team. Engineered for durability and ease of maintenance, it offers a clean design and straightforward access for daily operation — a reflection of our commitment to practical, long-lasting solutions that truly work for our clients.</p>
        </div>
        <div class="image-content">
          <img src="{% static 'images/featured1.png' %}" alt="Slide 1" />
        </div>
      </div>

      <!-- Slide 2 -->
      <div class="carousel-item">
        <div class="text-content">
          <h2>From Raw to Treated: Effluent Quality</h2>
          <p>The transformation made possible by our treatment process — from raw effluent (left) to clear, treated effluent (right). It demonstrate the system's efficiency in removing suspended solids, reducing turbidity, and meeting DENR effluent standards.<br><br>The result is clean, compliant water that's safe for discharge and can be reused for non-potable applications — reflecting our commitment to sustainable, high-performance treatment solutions.</p>
        </div>
        <div class="image-content">
          <img src="{% static 'images/ftr2replacement.png' %}" alt="Slide 2" />
        </div>
      </div>

      <!-- Slide 3 -->
      <div class="carousel-item">
        <div class="text-content">
          <h2>Blower System — Built for High Performance</h2>
          <p>A closer look at our blower system—the core of the biological treatment process. By delivering consistent airflow to sustain healthy microbial activity, it ensures the effective breakdown of organic matter while supporting long-term performance and reliability in operations.</p>
        </div>
        <div class="image-content">
          <img src="{% static 'images/featured3.png' %}" alt="Slide 3" />
        </div>
      </div>

    </div>

    <!-- Navigation Arrows -->
    <button class="nav prev">&#10094;</button>
    <button class="nav next">&#10095;</button>

    <!-- Dots -->
    <div class="dots">
      <span class="dot active"></span>
      <span class="dot"></span>
      <span class="dot"></span>
    </div>
  </div>

  <div class="introduction">
    <div class="container">
      <div id="text" class="collapsible-text">
        <div class="fade-out"></div>
        At Flow Industries OPC, we believe water is more than just a it's life itself. Every drop sustains people, communities, while also nurturing the environment we all depend on. Yet, with growing pressures from urbanization, agriculture, and industry, protecting this vital resource has never been more important.
        <br><br>
        That's why we go beyond traditional methods, combining innovation and sustainability to meet today's challenges. From removing visible impurities to tracking modern contaminants like microplasts and pharmaceuticals, our mission is clear: to provide safe, reliable, and future-ready water solutions.
        <br><br>
        When you partner with us, you're not just investing a treatment system—you're helping build a healthier community, a stronger economy, and a more sustainable tomorrow.
      </div>
      <button id="toggleBtn" class="see-more-btn">See More</button>
    </div>
  </div>

  <div class="title what-we-offer"><p>WHAT WE OFFER</p></div>
  <div class="grid-container">
    
    <a href="{% url 'services:consulting-services' %}">
      <div class="card consulting-services">
        <div class="img-container">
          <img src="{% static 'images/consulting-services.png' %}" alt="Consulting Services">
        </div>
        <p>Engineering and Consulting Services</p>
      </div>
    </a>
    <a href="{% url 'services:design-and-build' %}">
      <div class="card design-and-build">
        <div class="img-container">
          <img src="{% static 'images/design-and-build.png' %}" alt="Design and Build">
        </div>
        <p>Design and Build</p>
      </div>
    </a>
    <a href="{% url 'services:engineering-services' %}">
      <div class="card engineering-services">
        <div class="img-container">
          <img class="img-w-text" src="{% static 'images/support-service.png' %}" alt="Engineering Services">
        </div>
        <p>Support Service and Regulatory Assistance</p>
      </div>
    </a>
    <a href="{% url 'services:operations-and-maintenance' %}">
      <div class="card operations-and-maintenance">
        <div class="img-container">
          <img src="{% static 'images/opsandmaintenance.png' %}" alt="Operations and Maintenance">
        </div>
        <p>Operations and Maintenance</p>
      </div>
    </a>
    <a href="{% url 'services:rehabilitation' %}">
      <div class="card rehabilitation">
        <div class="img-container">
          <img src="{% static 'images/rehabilitation.png' %}" alt="Rehabilitation">
        </div>
        <p>Rehabilitation</p>
      </div>
    </a>
    <a href="{% url 'services:technology-upgrade' %}">
      <div class="card technology-upgrade">
        <div class="img-container">
          <img src="{% static 'images/TechnologyUpgrade.png' %}" alt="Technology Upgrade">
        </div>
        <p>Technology Upgrade</p>
      </div>
    </a>
  </div>

</div>

{% endblock %}

major_clients/templates/major_clients/major_clients.html
{% extends 'base.html' %}
{% block maincontent %}

<div class="major-clients">

  <div class="title"><p>McDonald's</p></div>
  <img src="../static/images/mcdonalds.png" alt="McDonald's">

</div>

{% endblock%}

services/templates/services/services.html
{% extends 'base.html' %}
{% block maincontent %}

<div>This is the services page</div>

{% endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
  <title>FIOPC</title>
  {% load static %}
  <link rel="icon" type="image/png" href="{% static 'images/icon.ico' %}">
</head>

<body>
  <div class="navbar-body">
    <nav>
      {% comment %} Logo {% endcomment %}
      <div class="logo-container">
        <a href="{% url 'home:index' %}" class="logo-container">
          <img src="{% static 'images/title.png' %}" alt="Flow Industries OPC">
        </a>
      </div>

      {% comment %} Links {% endcomment %}
      <ul class="nav-links">
        <li><a href="{% url 'home:index' %}">Home</a></li>
        <li class="dropdown">
          <a class="disabled" href="#">Services</a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'services:consulting-services' %}">Engineering and Consulting Services</a></li>
            <li><a href="{% url 'services:design-and-build' %}">Design and Build</a></li>
            <li><a href="{% url 'services:engineering-services' %}">Support Service and Regulatory Assistance</a></li>
            <li><a href="{% url 'services:operations-and-maintenance' %}">Operations and Maintenance</a></li>
            <li><a href="{% url 'services:rehabilitation' %}">Rehabilitation</a></li>
            <li><a href="{% url 'services:technology-upgrade' %}">Technology Upgrade</a></li>
          </ul>
        </li>
        <li><a href="{% url 'products:index' %}">Technology</a></li>
        <li><a href="{% url 'partners:index' %}">Projects</a></li>
        {% comment %} <li><a href="{% url 'major_clients:index' %}">Major Clients</a></li> {% endcomment %}
        <li><a href="{% url 'careers:index' %}">Careers</a></li>
        {% comment %} <li><a href="{% url 'licenses_certificates:index' %}">Licenses and Certs</a></li> {% endcomment %}
        <li><a href="{% url 'about:index' %}">About</a></li>
        <li><a href="{% url 'contacts:index' %}">Contact</a></li>
      </ul>

      <!-- Hamburger -->
      <div class="hamburger">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </nav>
  </div>

  {% block maincontent%}
  {% endblock %}

  {% comment %} <footer>
    <div class="company-name">
      <img src="{% static 'images/title.png' %}" alt="Flow Industries OPC">
    </div>
    <div class="info">
      <div class="col1">
        <i class='bx bxs-phone'></i>(02) 8296 2844<br>
        <i class='bx bxs-envelope'></i><a href="mailto:flowindustriesopc.@gmail.com">flowindustriesopc.@gmail.com</a>
      </div>
      <div class="col2">
        <i class='bx bxs-map'></i><a href="https://maps.app.goo.gl/uMwvVFSqtcEdNKKR9">Unit F 6/F Westgate Tower Condo, Investment Dr., Madrigal Business Park, Ayala-Alabang, Muntinlupa 1780</a>
      </div>
      <div class="col3">
        <i class='bx bxl-linkedin-square' ></i><a href="https://www.linkedin.com/company/flow-industries/">Flow Industries OPC</a><br>
        <i class='bx bxl-facebook-square' ></i><a href="https://www.facebook.com/share/172FWqAWTn/">FlowIndustriesOPC</a>
      </div>
    </div>
    <div class="copyright">
      Copyright 2025 &copy; FLOW INDUSTRIES OPC. All rights reserved.
    </div>
  </footer> {% endcomment %}

  <footer>
    <div class="columns">
      <div class="column-1">
        <img src="{% static 'images/title.png' %}" alt="Flow Industries OPC">
      </div>
      <div class="column-2">
        <i class='bx bxs-phone'></i>(02) 8296 2844<br>
        <i class='bx bxs-envelope'></i> <a href="mailto:flowindustriesopc.@gmail.com">flowindustriesopc.@gmail.com</a>
      </div>
      <div class="column-3">
        <i class='bx bxs-map'></i> <a href="https://maps.app.goo.gl/uMwvVFSqtcEdNKKR9">Unit F 6/F Westgate Tower Condo, Investment Dr., Madrigal Business Park, Ayala-Alabang, Muntinlupa 1780</a>
      </div>
      <div class="column-4">
        <i class='bx bxl-linkedin-square'></i> <a href="https://www.linkedin.com/company/flow-industries/">Flow Industries OPC</a><br>
        <i class='bx bxl-facebook-square'></i> <a href="https://www.facebook.com/share/172FWqAWTn/">FlowIndustriesOPC</a>
      </div>
    </div>
    <div class="copyright">
      <strong>
        Copyright 2025 &copy; FLOW INDUSTRIES OPC. All rights reserved.
      </strong>
    </div>
  </footer>


  <button id="backToTopBtn" title="Go to top">↑</button>

  <link rel="icon" href="{% static 'images/icon.ico' %}" type="image/x-icon">
  <script src="{% static 'index.js' %}"></script>
  <link rel = "stylesheet" href = "{% static 'style.css' %}">

  <script>
    document.addEventListener("DOMContentLoaded", function () {
      const nav = document.querySelector('.navbar-body nav');
      const hamburger = document.querySelector('.hamburger');
      if (hamburger && nav) {
        hamburger.addEventListener('click', () => {
          nav.classList.toggle('active');
        });
      }
    });
  </script>

  <script>
    window.addEventListener("scroll", function () {
      const navbar = document.querySelector(".navbar-body");
      if (window.scrollY > 10) {
        navbar.classList.add("scrolled");
      } else {
        navbar.classList.remove("scrolled");
      }
    });
  </script>

  <script>
    const backToTopBtn = document.getElementById("backToTopBtn");
    window.onscroll = function () {
      if (document.body.scrollTop > 100 || document.documentElement.scrollTop > 100) {
        backToTopBtn.style.display = "block";
      } else {
        backToTopBtn.style.display = "none";
      }
    };
    backToTopBtn.addEventListener("click", function () {
      window.scrollTo({
        top: 0,
        behavior: "smooth"
      });
    });
  </script>

</body>
</html>